In [2]:
import numpy as np
from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Conv2D, MaxPooling2D
from tensorflow.python.keras.layers import Activation, Dropout, Flatten, Dense
from tensorflow.python.keras.preprocessing import image
from tensorflow.python.keras.models import model_from_json
import cv2 as cv

In [4]:
#Создание генератора
datagen = ImageDataGenerator(rescale=1. / 255)

#Загрузка изображений
train_generator = datagen.flow_from_directory(
    'Data_for_lern_bin/train',
    target_size=(300, 300),
    batch_size=10,
    class_mode='binary')

val_generator = datagen.flow_from_directory(
    'Data_for_lern_bin/val',
    target_size=(300, 300),
    batch_size=10,
    class_mode='binary')

test_generator = datagen.flow_from_directory(
    'Data_for_lern_bin/test',
    target_size=(300, 300),
    batch_size=10,
    class_mode='binary')

Found 595 images belonging to 2 classes.
Found 163 images belonging to 2 classes.
Found 111 images belonging to 2 classes.


In [8]:
model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=(300, 300, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('softmax'))

In [9]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [10]:
# Размер мини-выборки
batch_size = 10
# Количество изображений для обучения
nb_train_samples = 595
# Количество изображений для проверки
nb_validation_samples = 163
# Количество изображений для тестирования
nb_test_samples = 111

model.fit_generator(
    train_generator,
    steps_per_epoch=nb_train_samples // batch_size,
    epochs=6,
    validation_data=val_generator,
    validation_steps=nb_validation_samples // batch_size)

# Генерируем описание модели в формате json
model_json = model.to_json()
# Записываем модель в файл
json_file = open("model_gen_j_tom_bin.json", "w")
json_file.write(model_json)
json_file.close()
model.save_weights("model_gen_h_tom_bin.h5")

Epoch 1/6
59/59 [==============================] - 463s 8s/step - loss: 9.2407 - acc: 0.4204 - val_loss: 10.3626 - val_acc: 0.3500
Epoch 2/6
59/59 [==============================] - 452s 8s/step - loss: 9.1866 - acc: 0.4238 - val_loss: 10.3626 - val_acc: 0.3500
Epoch 3/6
59/59 [==============================] - 451s 8s/step - loss: 9.2141 - acc: 0.4220 - val_loss: 10.3626 - val_acc: 0.3500
Epoch 4/6
59/59 [==============================] - 454s 8s/step - loss: 9.1601 - acc: 0.4254 - val_loss: 10.3626 - val_acc: 0.3500
Epoch 5/6
59/59 [==============================] - 452s 8s/step - loss: 9.3488 - acc: 0.4136 - val_loss: 10.3626 - val_acc: 0.3500
Epoch 6/6
59/59 [==============================] - 452s 8s/step - loss: 9.2150 - acc: 0.4220 - val_loss: 10.3626 - val_acc: 0.3500


In [ ]:
scores = model.evaluate_generator(test_generator, nb_test_samples // batch_size)
print("Аккуратность на тестовых данных: %.2f%%" % (scores[1]*100))

In [3]:
#download net
#загружаем нейронную сеть
json_file = open("save_model/model_gen_j_tom83.json", "r")
loaded_model_json = json_file.read()
json_file.close()

model = model_from_json(loaded_model_json)
model.load_weights("save_model/model_gen_h_tom_83.h5")

#компилиркем нейроннуюсеть
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [4]:
#url_img = '17.tif'
#url_img = 'soya.jpg'
#img = cv.imread(url_img)
#img = cv.resize(img, (240, 245))
#img = img / 255
#img = np.expand_dims(img, axis=0)
cap = cv.VideoCapture('C:/Users/Sergey/Pictures/Dataset_fablab/Test_Videos/1.mp4')

#result = model.predict(img)
#print(int(result[0][0]))

while True:
    _, img = cap.read()
    
    img = cv.resize(img, (300, 300))
    cv.imshow('img', img)
    img = img / 255
    img = np.expand_dims(img, axis=0)
    
    result = model.predict(img)
    print(result)
    if cv.waitKey(30) == ord('q'):
          break
cap.release()
cv.destroyAllWindows()

[[0.00475625 0.13133259 0.8627567  0.00115442]]
[[0.00470185 0.13127117 0.86289227 0.00113467]]
[[0.00484538 0.13148278 0.86244375 0.0012281 ]]
[[0.0046956  0.12435517 0.86970365 0.00124558]]
[[0.00484064 0.13199858 0.8619766  0.00118413]]
[[0.00458781 0.12436521 0.869879   0.00116798]]
[[0.00443345 0.11895541 0.8754546  0.00115658]]
[[0.00461877 0.1262185  0.86797637 0.00118643]]
[[0.0047501  0.12953193 0.8645162  0.00120177]]
[[0.00492312 0.13684343 0.85704356 0.00118985]]
[[0.00483491 0.1366964  0.8573174  0.00115134]]
[[0.00473353 0.13292202 0.8611981  0.00114633]]
[[0.00465791 0.12906133 0.8651172  0.00116367]]
[[0.00482425 0.13260086 0.8613642  0.00121068]]
[[0.00455094 0.12805282 0.8662804  0.00111587]]
[[0.00462297 0.12671377 0.86748594 0.00117735]]
[[0.00496668 0.13830212 0.8555516  0.00117964]]
[[0.00516692 0.14531809 0.84831804 0.00119695]]
[[0.0048593  0.1380556  0.8559406  0.00114454]]
[[0.00498767 0.13926262 0.8545591  0.00119059]]
[[0.00480149 0.13700914 0.857049   0.001

[[0.00694285 0.10276081 0.8845983  0.00569806]]
[[0.00611209 0.0986265  0.89126503 0.0039964 ]]
[[0.00628728 0.10868985 0.88188237 0.00314046]]
[[0.00695117 0.10719924 0.8817822  0.00406749]]
[[0.00704194 0.11784642 0.8716689  0.0034428 ]]
[[0.00645672 0.12003972 0.8711262  0.00237738]]
[[0.00615804 0.11514438 0.87635034 0.00234726]]
[[0.00519856 0.09616947 0.896328   0.00230405]]
[[0.00492844 0.0855173  0.90711397 0.00244027]]
[[0.00386475 0.08109972 0.9131727  0.00186294]]
[[0.00391023 0.08307973 0.9112562  0.00175384]]
[[0.00369866 0.08024148 0.91442436 0.00163552]]
[[0.00354077 0.07447059 0.9203617  0.00162702]]
[[0.00357107 0.08001034 0.9149554  0.00146318]]
[[0.0036586  0.07618374 0.9186573  0.00150032]]
[[0.00319338 0.06736524 0.9279287  0.00151275]]
[[0.00288442 0.06963089 0.9261737  0.00131103]]
[[0.00293616 0.06853292 0.92723143 0.0012994 ]]
[[0.00278377 0.06349    0.9324339  0.0012923 ]]
[[0.00276865 0.07100565 0.9249967  0.00122902]]
[[0.00274996 0.06963079 0.9264023  0.001

error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'


In [18]:
url_img = '333.jpg'
Frame = cv.imread(url_img)
img = cv.resize(Frame, (300, 300))
img = img / 255
img = np.expand_dims(img, axis=0)
#cap = cv.VideoCapture('C:/Users/Sergey/Pictures/Dataset_fablab/Test_Videos/1.mp4')

result = model.predict(img)
print(result)

max = 0
for i in result[0]:
    if (i > max):
        max = i
print(max)
for i in range(len(result[0])):
    if result[0][i] == max:
        print(i - 1)

while True:
    
    cv.imshow('img', Frame)
    if cv.waitKey(30) == ord('q'):
          break
cv.destroyAllWindows()

[[0.00471747 0.07794309 0.9150861  0.00225331]]
0.9150861
2
